// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(VietImmerseDbContext))]
    [Migration("20260518072857_AddMessageTypeAndBookingToMessage")]
    partial class AddMessageTypeAndBookingToMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_status", new[] { "active", "inactive", "suspended", "pending_verification" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "pending", "confirmed", "completed", "cancelled", "no_show" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "content_category_type", new[] { "shopping", "taxi", "dining", "greeting", "work", "culture", "grammar", "pronunciation", "daily_life" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "learner_level", new[] { "basic", "intermediate", "advanced" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", new[] { "system", "booking_reminder", "new_message", "review_received", "progress_milestone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "partner_profile_status", new[] { "draft", "pending_review", "approved", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "learner", "partner", "guest" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaCategory", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("MediaId", "CategoryId")
                        .HasName("media_category_pkey");

                    b.HasIndex(new[] { "CategoryId" }, "idx_media_category_category");

                    b.ToTable("media_category", (string)null);
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("learner_id");

                    b.Property<string>("LearnerNotes")
                        .HasColumnType("text")
                        .HasColumnName("learner_notes");

                    b.Property<string>("MeetingUrl")
                        .HasColumnType("text")
                        .HasColumnName("meeting_url");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerNotes")
                        .HasColumnType("text")
                        .HasColumnName("partner_notes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BookingId")
                        .HasName("bookings_pkey");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("ConversationId");

                    b.HasIndex(new[] { "LearnerId" }, "idx_bookings_learner");

                    b.HasIndex(new[] { "PartnerId" }, "idx_bookings_partner");

                    b.HasIndex(new[] { "StartTime" }, "idx_bookings_time");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("backend.Models.ContentCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_vi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId")
                        .HasName("content_categories_pkey");

                    b.HasIndex(new[] { "Slug" }, "content_categories_slug_key")
                        .IsUnique();

                    b.ToTable("content_categories");
                });

            modelBuilder.Entity("backend.Models.ContentLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sort_order");

                    b.HasKey("LevelId")
                        .HasName("content_levels_pkey");

                    b.ToTable("content_levels");
                });

            modelBuilder.Entity("backend.Models.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("learner_id");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.HasKey("ConversationId")
                        .HasName("conversations_pkey");

                    b.HasIndex(new[] { "LearnerId", "PartnerId" }, "conversations_learner_id_partner_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "LearnerId" }, "idx_conversations_learner");

                    b.HasIndex(new[] { "PartnerId" }, "idx_conversations_partner");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("backend.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("ExplanationJa")
                        .HasColumnType("text")
                        .HasColumnName("explanation_ja");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionTextJa")
                        .HasColumnType("text")
                        .HasColumnName("question_text_ja");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("ExerciseId")
                        .HasName("exercises_pkey");

                    b.HasIndex(new[] { "MediaId" }, "idx_exercises_media");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("backend.Models.LearnerProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<string>("Goals")
                        .HasColumnType("text")
                        .HasColumnName("goals");

                    b.Property<int?>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak");

                    b.Property<string>("NativeLanguage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("native_language")
                        .HasDefaultValueSql("'ja'::character varying");

                    b.Property<decimal?>("TotalStudyHours")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_study_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("VideosCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("videos_completed");

                    b.HasKey("ProfileId")
                        .HasName("learner_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "learner_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("learner_profiles");
                });

            modelBuilder.Entity("backend.Models.ListeningError", b =>
                {
                    b.Property<Guid>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("error_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CorrectText")
                        .HasColumnType("text")
                        .HasColumnName("correct_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("error_type");

                    b.Property<string>("LearnerHeard")
                        .HasColumnType("text")
                        .HasColumnName("learner_heard");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<bool?>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reviewed");

                    b.Property<Guid?>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ErrorId")
                        .HasName("listening_errors_pkey");

                    b.HasIndex("MediaId");

                    b.HasIndex("SegmentId");

                    b.HasIndex(new[] { "ErrorType" }, "idx_listening_errors_type");

                    b.HasIndex(new[] { "UserId" }, "idx_listening_errors_user");

                    b.ToTable("listening_errors");
                });

            modelBuilder.Entity("backend.Models.MediaContent", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("media_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("level_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("SourcePlatform")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_platform");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("MediaId")
                        .HasName("media_content_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "LevelId" }, "idx_media_content_level");

                    b.HasIndex(new[] { "IsPublished", "PublishedAt" }, "idx_media_content_published")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "MediaType" }, "idx_media_content_type");

                    b.ToTable("media_content");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentTranslated")
                        .HasColumnType("text")
                        .HasColumnName("content_translated");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("message_type");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId")
                        .HasName("messages_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex(new[] { "ConversationId", "SentAt" }, "idx_messages_conversation");

                    b.HasIndex(new[] { "SenderId" }, "idx_messages_sender");

                    b.HasIndex(new[] { "ConversationId", "IsRead" }, "idx_messages_unread")
                        .HasFilter("(is_read = false)");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "idx_notifications_user")
                        .IsDescending(false, false, true);

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("backend.Models.PartnerProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvailabilityJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("availability_json");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("HourlyRate")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("intro_video_url");

                    b.Property<decimal?>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<int?>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.PrimitiveCollection<List<string>>("Specialties")
                        .HasColumnType("text[]")
                        .HasColumnName("specialties");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId")
                        .HasName("partner_profiles_pkey");

                    b.HasIndex(new[] { "RatingAvg" }, "idx_partner_profiles_rating")
                        .IsDescending();

                    b.HasIndex(new[] { "UserId" }, "partner_profiles_user_id_key")
                        .IsUnique();

                    b.ToTable("partner_profiles");
                });

            modelBuilder.Entity("backend.Models.QuizAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selected_answer");

                    b.Property<int?>("TimeTakenMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_taken_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AttemptId")
                        .HasName("quiz_attempts_pkey");

                    b.HasIndex(new[] { "UserId", "IsCorrect" }, "idx_quiz_attempts_correct");

                    b.HasIndex(new[] { "ExerciseId" }, "idx_quiz_attempts_exercise");

                    b.HasIndex(new[] { "UserId" }, "idx_quiz_attempts_user");

                    b.ToTable("quiz_attempts");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("review_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("ReviewId")
                        .HasName("reviews_pkey");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "BookingId" }, "idx_reviews_booking");

                    b.HasIndex(new[] { "Rating" }, "idx_reviews_rating");

                    b.HasIndex(new[] { "RevieweeId" }, "idx_reviews_reviewee");

                    b.HasIndex(new[] { "BookingId" }, "reviews_booking_id_key")
                        .IsUnique();

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("backend.Models.ShadowingLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AccuracyScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("accuracy_score");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PracticedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("practiced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("text")
                        .HasColumnName("recording_url");

                    b.Property<Guid?>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("shadowing_logs_pkey");

                    b.HasIndex("SegmentId");

                    b.HasIndex(new[] { "MediaId" }, "idx_shadowing_logs_media");

                    b.HasIndex(new[] { "UserId" }, "idx_shadowing_logs_user");

                    b.ToTable("shadowing_logs");
                });

            modelBuilder.Entity("backend.Models.Transcript", b =>
                {
                    b.Property<Guid>("TranscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transcript_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_text");

                    b.Property<bool?>("HasTimestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_timestamps");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language")
                        .HasDefaultValueSql("'vi'::character varying");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TranscriptId")
                        .HasName("transcripts_pkey");

                    b.HasIndex(new[] { "MediaId" }, "transcripts_media_id_key")
                        .IsUnique();

                    b.ToTable("transcripts");
                });

            modelBuilder.Entity("backend.Models.TranscriptSegment", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EndMs")
                        .HasColumnType("integer")
                        .HasColumnName("end_ms");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<string>("Speaker")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("speaker");

                    b.Property<int>("StartMs")
                        .HasColumnType("integer")
                        .HasColumnName("start_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("TranscriptId")
                        .HasColumnType("uuid")
                        .HasColumnName("transcript_id");

                    b.HasKey("SegmentId")
                        .HasName("transcript_segments_pkey");

                    b.HasIndex(new[] { "TranscriptId", "SegmentIndex" }, "idx_segments_order")
                        .IsUnique();

                    b.HasIndex(new[] { "TranscriptId", "StartMs", "EndMs" }, "idx_segments_time");

                    b.ToTable("transcript_segments");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_status");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CountryCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("country_code")
                        .HasDefaultValueSql("'JP'::character varying");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNameJa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name_ja");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<string>("LanguagePref")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_pref")
                        .HasDefaultValueSql("'ja'::character varying");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.UserSetting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("setting_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("AutoPlayNext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_play_next");

                    b.Property<int?>("DailyGoalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("daily_goal_minutes");

                    b.Property<bool?>("NotifyBookingReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_booking_reminder");

                    b.Property<bool?>("NotifyEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_email");

                    b.Property<bool?>("NotifyPush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_push");

                    b.Property<bool?>("NotifySms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notify_sms");

                    b.Property<decimal?>("PlaybackSpeed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("playback_speed");

                    b.Property<bool?>("ShowJapaneseSubs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_japanese_subs");

                    b.Property<string>("Theme")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme")
                        .HasDefaultValueSql("'light'::character varying");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone")
                        .HasDefaultValueSql("'Asia/Tokyo'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SettingId")
                        .HasName("user_settings_pkey");

                    b.HasIndex(new[] { "UserId" }, "user_settings_user_id_key")
                        .IsUnique();

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("backend.Models.ViewingHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<int?>("LastPositionMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_position_ms");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<int?>("ReplayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("replay_count");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId")
                        .HasName("viewing_history_pkey");

                    b.HasIndex(new[] { "UserId", "IsCompleted" }, "idx_viewing_history_completed");

                    b.HasIndex(new[] { "MediaId" }, "idx_viewing_history_media");

                    b.HasIndex(new[] { "UserId" }, "idx_viewing_history_user");

                    b.HasIndex(new[] { "UserId", "MediaId" }, "viewing_history_user_id_media_id_key")
                        .IsUnique();

                    b.ToTable("viewing_history");
                });

            modelBuilder.Entity("MediaCategory", b =>
                {
                    b.HasOne("backend.Models.ContentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_category_category_id_fkey");

                    b.HasOne("backend.Models.MediaContent", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_category_media_id_fkey");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.User", "CancelledByNavigation")
                        .WithMany("BookingCancelledByNavigations")
                        .HasForeignKey("CancelledBy")
                        .HasConstraintName("bookings_cancelled_by_fkey");

                    b.HasOne("backend.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId");

                    b.HasOne("backend.Models.User", "Learner")
                        .WithMany("BookingLearners")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookings_learner_id_fkey");

                    b.HasOne("backend.Models.User", "Partner")
                        .WithMany("BookingPartners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookings_partner_id_fkey");

                    b.Navigation("CancelledByNavigation");

                    b.Navigation("Conversation");

                    b.Navigation("Learner");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("backend.Models.Conversation", b =>
                {
                    b.HasOne("backend.Models.User", "Learner")
                        .WithMany("ConversationLearners")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("conversations_learner_id_fkey");

                    b.HasOne("backend.Models.User", "Partner")
                        .WithMany("ConversationPartners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("conversations_partner_id_fkey");

                    b.Navigation("Learner");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("backend.Models.Exercise", b =>
                {
                    b.HasOne("backend.Models.MediaContent", "Media")
                        .WithMany("Exercises")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exercises_media_id_fkey");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("backend.Models.LearnerProfile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("LearnerProfile")
                        .HasForeignKey("backend.Models.LearnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("learner_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.ListeningError", b =>
                {
                    b.HasOne("backend.Models.MediaContent", "Media")
                        .WithMany("ListeningErrors")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("listening_errors_media_id_fkey");

                    b.HasOne("backend.Models.TranscriptSegment", "Segment")
                        .WithMany("ListeningErrors")
                        .HasForeignKey("SegmentId")
                        .HasConstraintName("listening_errors_segment_id_fkey");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ListeningErrors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("listening_errors_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("Segment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.MediaContent", b =>
                {
                    b.HasOne("backend.Models.User", "CreatedByNavigation")
                        .WithMany("MediaContents")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("media_content_created_by_fkey");

                    b.HasOne("backend.Models.ContentLevel", "Level")
                        .WithMany("MediaContents")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("media_content_level_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("backend.Models.Message", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("backend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("messages_conversation_id_fkey");

                    b.HasOne("backend.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("messages_sender_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.PartnerProfile", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("PartnerProfile")
                        .HasForeignKey("backend.Models.PartnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("partner_profiles_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.QuizAttempt", b =>
                {
                    b.HasOne("backend.Models.Exercise", "Exercise")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_attempts_exercise_id_fkey");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_attempts_user_id_fkey");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("backend.Models.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_booking_id_fkey");

                    b.HasOne("backend.Models.User", "Reviewee")
                        .WithMany("ReviewReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewee_id_fkey");

                    b.HasOne("backend.Models.User", "Reviewer")
                        .WithMany("ReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewer_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("backend.Models.ShadowingLog", b =>
                {
                    b.HasOne("backend.Models.MediaContent", "Media")
                        .WithMany("ShadowingLogs")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shadowing_logs_media_id_fkey");

                    b.HasOne("backend.Models.TranscriptSegment", "Segment")
                        .WithMany("ShadowingLogs")
                        .HasForeignKey("SegmentId")
                        .HasConstraintName("shadowing_logs_segment_id_fkey");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ShadowingLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shadowing_logs_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("Segment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Transcript", b =>
                {
                    b.HasOne("backend.Models.MediaContent", "Media")
                        .WithOne("Transcript")
                        .HasForeignKey("backend.Models.Transcript", "MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transcripts_media_id_fkey");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("backend.Models.TranscriptSegment", b =>
                {
                    b.HasOne("backend.Models.Transcript", "Transcript")
                        .WithMany("TranscriptSegments")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transcript_segments_transcript_id_fkey");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("backend.Models.UserSetting", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("backend.Models.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_settings_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.ViewingHistory", b =>
                {
                    b.HasOne("backend.Models.MediaContent", "Media")
                        .WithMany("ViewingHistories")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("viewing_history_media_id_fkey");

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ViewingHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("viewing_history_user_id_fkey");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("backend.Models.ContentLevel", b =>
                {
                    b.Navigation("MediaContents");
                });

            modelBuilder.Entity("backend.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("backend.Models.Exercise", b =>
                {
                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("backend.Models.MediaContent", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("ListeningErrors");

                    b.Navigation("ShadowingLogs");

                    b.Navigation("Transcript");

                    b.Navigation("ViewingHistories");
                });

            modelBuilder.Entity("backend.Models.Transcript", b =>
                {
                    b.Navigation("TranscriptSegments");
                });

            modelBuilder.Entity("backend.Models.TranscriptSegment", b =>
                {
                    b.Navigation("ListeningErrors");

                    b.Navigation("ShadowingLogs");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("BookingCancelledByNavigations");

                    b.Navigation("BookingLearners");

                    b.Navigation("BookingPartners");

                    b.Navigation("ConversationLearners");

                    b.Navigation("ConversationPartners");

                    b.Navigation("LearnerProfile");

                    b.Navigation("ListeningErrors");

                    b.Navigation("MediaContents");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("PartnerProfile");

                    b.Navigation("QuizAttempts");

                    b.Navigation("ReviewReviewees");

                    b.Navigation("ReviewReviewers");

                    b.Navigation("ShadowingLogs");

                    b.Navigation("UserSetting");

                    b.Navigation("ViewingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
